//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChapterHelper.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChapterHelper.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add chapter.
        /// </summary>
        public static string AddChapter {
            get {
                return ResourceManager.GetString("AddChapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All types (*.*).
        /// </summary>
        public static string AllTypesFileFilter {
            get {
                return ResourceManager.GetString("AllTypesFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chapter Helper.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse....
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chapters.
        /// </summary>
        public static string Chapters {
            get {
                return ResourceManager.GetString("Chapters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Writing File.
        /// </summary>
        public static string ErrorWritingFile {
            get {
                return ResourceManager.GetString("ErrorWritingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Chapters.
        /// </summary>
        public static string ExportChapters {
            get {
                return ResourceManager.GetString("ExportChapters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export qpfile.
        /// </summary>
        public static string ExportQpFile {
            get {
                return ResourceManager.GetString("ExportQpFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Timecodes.
        /// </summary>
        public static string ExportTimecodes {
            get {
                return ResourceManager.GetString("ExportTimecodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input duration.
        /// </summary>
        public static string InputDuration {
            get {
                return ResourceManager.GetString("InputDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input end time.
        /// </summary>
        public static string InputEndTime {
            get {
                return ResourceManager.GetString("InputEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input first frame.
        /// </summary>
        public static string InputFirstFrame {
            get {
                return ResourceManager.GetString("InputFirstFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input frame rate.
        /// </summary>
        public static string InputFrameRate {
            get {
                return ResourceManager.GetString("InputFrameRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input last frame.
        /// </summary>
        public static string InputLastFrame {
            get {
                return ResourceManager.GetString("InputLastFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input length.
        /// </summary>
        public static string InputLength {
            get {
                return ResourceManager.GetString("InputLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input start time.
        /// </summary>
        public static string InputStartTime {
            get {
                return ResourceManager.GetString("InputStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load from trims.
        /// </summary>
        public static string LoadFromTrims {
            get {
                return ResourceManager.GetString("LoadFromTrims", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the AviSynth trims to create chapters from below:.
        /// </summary>
        public static string LoadFromTrimsDescription {
            get {
                return ResourceManager.GetString("LoadFromTrimsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load From AviSynth Trims.
        /// </summary>
        public static string LoadFromTrimsHeader {
            get {
                return ResourceManager.GetString("LoadFromTrimsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matroska Chapter File (.xml).
        /// </summary>
        public static string MatroskaChapterFileFilter {
            get {
                return ResourceManager.GetString("MatroskaChapterFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not all required fields were filled out. Please re-check the chapters..
        /// </summary>
        public static string MissingInformationDescription {
            get {
                return ResourceManager.GetString("MissingInformationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Information.
        /// </summary>
        public static string MissingInformationHeading {
            get {
                return ResourceManager.GetString("MissingInformationHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MKVToolNix Directory.
        /// </summary>
        public static string MkvToolNixDirectory {
            get {
                return ResourceManager.GetString("MkvToolNixDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No usable MKVToolNix installation could be found..
        /// </summary>
        public static string MkvToolNixNotReadyDescription {
            get {
                return ResourceManager.GetString("MkvToolNixNotReadyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MKVToolNix Not Ready.
        /// </summary>
        public static string MkvToolNixNotReadyHeading {
            get {
                return ResourceManager.GetString("MkvToolNixNotReadyHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output duration.
        /// </summary>
        public static string OutputDuration {
            get {
                return ResourceManager.GetString("OutputDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output end time.
        /// </summary>
        public static string OutputEndTime {
            get {
                return ResourceManager.GetString("OutputEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output first frame.
        /// </summary>
        public static string OutputFirstFrame {
            get {
                return ResourceManager.GetString("OutputFirstFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output frame rate.
        /// </summary>
        public static string OutputFrameRate {
            get {
                return ResourceManager.GetString("OutputFrameRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output last frame.
        /// </summary>
        public static string OutputLastFrame {
            get {
                return ResourceManager.GetString("OutputLastFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output length.
        /// </summary>
        public static string OutputLength {
            get {
                return ResourceManager.GetString("OutputLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output start time.
        /// </summary>
        public static string OutputStartTime {
            get {
                return ResourceManager.GetString("OutputStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Times Unspecified.
        /// </summary>
        public static string OutputTimesUnspecified {
            get {
                return ResourceManager.GetString("OutputTimesUnspecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All output times except the last one have to be specified..
        /// </summary>
        public static string OutputTimesUnspecifiedDescription {
            get {
                return ResourceManager.GetString("OutputTimesUnspecifiedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to qpfile.
        /// </summary>
        public static string QpFile {
            get {
                return ResourceManager.GetString("QpFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to qpfile (.txt).
        /// </summary>
        public static string QpFileFilter {
            get {
                return ResourceManager.GetString("QpFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove chapter.
        /// </summary>
        public static string RemoveChapter {
            get {
                return ResourceManager.GetString("RemoveChapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split Error.
        /// </summary>
        public static string SplitError {
            get {
                return ResourceManager.GetString("SplitError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split File.
        /// </summary>
        public static string SplitFile {
            get {
                return ResourceManager.GetString("SplitFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following delay was recognized on the input file. You can change or accept it now..
        /// </summary>
        public static string SplitFileSettingsDialogDescription {
            get {
                return ResourceManager.GetString("SplitFileSettingsDialogDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split File - Settings.
        /// </summary>
        public static string SplitFileSettingsDialogHeader {
            get {
                return ResourceManager.GetString("SplitFileSettingsDialogHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timecodes.
        /// </summary>
        public static string Timecodes {
            get {
                return ResourceManager.GetString("Timecodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timecodes File (.txt).
        /// </summary>
        public static string TimecodesFileFilter {
            get {
                return ResourceManager.GetString("TimecodesFileFilter", resourceCulture);
            }
        }
    }
}
